version: '3'
services:
  web:
    build: ./php
    ports:
    - "9001:9001"
    links:
    - redis
  notifier:
    build: ./python
    links:
    - redis
  redis:
    image: lhzsantana/redis-standalone